# Generated by Django 3.2.5 on 2022-07-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_grade', models.IntegerField(default=1)),
                ('user_maxcredit', models.IntegerField(default=19)),
                ('user_password', models.CharField(max_length=15)),
                ('course', models.ManyToManyField(to='course.Course')),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.major')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
